import { PrivilegeKey } from '@/types/privileges';

export interface Permission {
  key: string;
  label: string;
}

export interface PermissionGroup {
  title: string;
  module: PrivilegeKey;
  permissions: Permission[];
}

export const permissionGroups: PermissionGroup[] = [
  {
    title: 'Checkout & POS',
    module: 'checkout' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Checkout' },
      { key: 'view_orders', label: 'View Orders' },
      { key: 'create_orders', label: 'Create Orders' },
      { key: 'edit_orders', label: 'Edit Orders' },
      { key: 'delete_orders', label: 'Delete Orders' },
      { key: 'process_payment', label: 'Process Payment' },
      { key: 'view_customer_info', label: 'View Customer Info' },
      { key: 'edit_customer_info', label: 'Edit Customer Info' },
      { key: 'delete_pending_orders', label: 'Delete Pending Orders' },
      { key: 'apply_discount', label: 'Apply Discount' },
    ],
  },
  {
    title: 'Staff Management',
    module: 'staff_management' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Staff Management' },
      { key: 'add_new_staff', label: 'Add New Staff' },
      { key: 'assign_roles', label: 'Assign Roles' },
      { key: 'view_permissions', label: 'View Permissions' },
      { key: 'view_accounts', label: 'View Accounts' },
      { key: 'edit_accounts', label: 'Edit Accounts' },
      { key: 'delete_staff', label: 'Delete Staff' },
      { key: 'edit_permissions', label: 'Edit Permissions' },
      { key: 'view_activity_logs', label: 'View Activity Logs' },
    ],
  },
  {
    title: 'Inventory Management',
    module: 'inventory' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Inventory' },
      { key: 'view_products', label: 'View Products' },
      { key: 'add_products', label: 'Add Products' },
      { key: 'edit_products', label: 'Edit Products' },
      { key: 'delete_products', label: 'Delete Products' },
      { key: 'import_products', label: 'Import Products' },
      { key: 'export_products', label: 'Export Products' },
      { key: 'manage_categories', label: 'Manage Categories' },
      { key: 'view_stock_levels', label: 'View Stock Levels' },
      { key: 'update_stock', label: 'Update Stock' },
    ],
  },
  {
    title: 'Transactions',
    module: 'transactions' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Transactions' },
      { key: 'view', label: 'View Transactions' },
      { key: 'refund', label: 'Process Refunds' },
      { key: 'export', label: 'Export Transactions' },
      { key: 'view_details', label: 'View Details' },
      { key: 'process_refund', label: 'Process Refund' },
      { key: 'view_receipts', label: 'View Receipts' },
      { key: 'print_receipts', label: 'Print Receipts' },
    ],
  },
  {
    title: 'Discounts',
    module: 'discounts' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Discounts' },
      { key: 'create_discount', label: 'Create Discounts' },
      { key: 'delete_discount', label: 'Delete Discounts' },
      { key: 'edit_discount', label: 'Edit Discounts' },
      { key: 'view_discounts', label: 'View Discounts' },
      { key: 'apply_discount', label: 'Apply Discounts' },
      { key: 'manage_discount_rules', label: 'Manage Discount Rules' },
    ],
  },
  {
    title: 'Company Dashboard',
    module: 'company_dashboard' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Company Dashboard' },
      { key: 'view_reports', label: 'View Reports' },
      { key: 'export_reports', label: 'Export Reports' },
      { key: 'view_analytics', label: 'View Analytics' },
      { key: 'view_revenue_data', label: 'View Revenue Data' },
      { key: 'view_performance_metrics', label: 'View Performance Metrics' },
    ],
  },
  {
    title: 'Shop Dashboard',
    module: 'shop_dashboard' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Shop Dashboard' },
      { key: 'view_sales_data', label: 'View Sales Data' },
      { key: 'manage_daily_targets', label: 'Manage Daily Targets' },
      { key: 'view_shop_performance', label: 'View Shop Performance' },
      { key: 'view_staff_performance', label: 'View Staff Performance' },
      { key: 'view_customer_metrics', label: 'View Customer Metrics' },
    ],
  },
  {
    title: 'Financial Overview',
    module: 'financial_overview' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Financial Overview' },
      { key: 'view_profits', label: 'View Profits' },
      { key: 'export_financial_data', label: 'Export Financial Data' },
      { key: 'view_revenue_reports', label: 'View Revenue Reports' },
      { key: 'view_expense_reports', label: 'View Expense Reports' },
      { key: 'view_profit_margins', label: 'View Profit Margins' },
    ],
  },
  {
    title: 'POS Terminal',
    module: 'pos_terminal' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access POS Terminal' },
      { key: 'park_sale', label: 'Park Sale' },
      { key: 'hold_order', label: 'Hold Order' },
      { key: 'resume_order', label: 'Resume Order' },
      { key: 'process_sale', label: 'Process Sale' },
      { key: 'view_cart', label: 'View Cart' },
      { key: 'edit_cart', label: 'Edit Cart' },
      { key: 'apply_promotions', label: 'Apply Promotions' },
    ],
  },
  {
    title: 'Products',
    module: 'products' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Products' },
      { key: 'view_products', label: 'View Products' },
      { key: 'add_products', label: 'Add Products' },
      { key: 'edit_products', label: 'Edit Products' },
      { key: 'delete_products', label: 'Delete Products' },
      { key: 'import_products', label: 'Import Products' },
      { key: 'export_products', label: 'Export Products' },
      { key: 'manage_categories', label: 'Manage Categories' },
      { key: 'manage_pricing', label: 'Manage Pricing' },
      { key: 'manage_inventory', label: 'Manage Inventory' },
    ],
  },
  {
    title: 'Orders',
    module: 'orders' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Orders' },
      { key: 'view_orders', label: 'View Orders' },
      { key: 'create_orders', label: 'Create Orders' },
      { key: 'edit_orders', label: 'Edit Orders' },
      { key: 'delete_orders', label: 'Delete Orders' },
      { key: 'process_orders', label: 'Process Orders' },
      { key: 'cancel_orders', label: 'Cancel Orders' },
      { key: 'export_orders', label: 'Export Orders' },
      { key: 'view_order_history', label: 'View Order History' },
    ],
  },
  {
    title: 'Users',
    module: 'users' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Users' },
      { key: 'add_users', label: 'Add Users' },
      { key: 'edit_users', label: 'Edit Users' },
      { key: 'delete_users', label: 'Delete Users' },
      { key: 'view_users', label: 'View Users' },
      { key: 'manage_user_roles', label: 'Manage User Roles' },
      { key: 'view_user_activity', label: 'View User Activity' },
    ],
  },
  {
    title: 'Shops',
    module: 'shops' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Shops' },
      { key: 'add_shops', label: 'Add Shops' },
      { key: 'edit_shops', label: 'Edit Shops' },
      { key: 'delete_shops', label: 'Delete Shops' },
      { key: 'view_shops', label: 'View Shops' },
      { key: 'manage_shop_settings', label: 'Manage Shop Settings' },
      { key: 'view_shop_performance', label: 'View Shop Performance' },
    ],
  },
  {
    title: 'Shoppers',
    module: 'shoppers' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Shoppers' },
      { key: 'add_shoppers', label: 'Add Shoppers' },
      { key: 'edit_shoppers', label: 'Edit Shoppers' },
      { key: 'delete_shoppers', label: 'Delete Shoppers' },
      { key: 'view_shoppers', label: 'View Shoppers' },
      { key: 'manage_shopper_data', label: 'Manage Shopper Data' },
      { key: 'view_shopper_history', label: 'View Shopper History' },
    ],
  },
  {
    title: 'Wallet',
    module: 'wallet' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Wallet' },
      { key: 'view_wallet', label: 'View Wallet' },
      { key: 'add_funds', label: 'Add Funds' },
      { key: 'remove_funds', label: 'Remove Funds' },
      { key: 'process_payout', label: 'Process Payout' },
      { key: 'view_transactions', label: 'View Transactions' },
      { key: 'manage_wallet_settings', label: 'Manage Wallet Settings' },
    ],
  },
  {
    title: 'Refunds',
    module: 'refunds' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Refunds' },
      { key: 'view_refunds', label: 'View Refunds' },
      { key: 'process_refunds', label: 'Process Refunds' },
      { key: 'approve_refunds', label: 'Approve Refunds' },
      { key: 'reject_refunds', label: 'Reject Refunds' },
      { key: 'export_refunds', label: 'Export Refunds' },
      { key: 'view_refund_history', label: 'View Refund History' },
    ],
  },
  {
    title: 'Tickets',
    module: 'tickets' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Tickets' },
      { key: 'view_tickets', label: 'View Tickets' },
      { key: 'create_tickets', label: 'Create Tickets' },
      { key: 'edit_tickets', label: 'Edit Tickets' },
      { key: 'delete_tickets', label: 'Delete Tickets' },
      { key: 'assign_tickets', label: 'Assign Tickets' },
      { key: 'resolve_tickets', label: 'Resolve Tickets' },
      { key: 'export_tickets', label: 'Export Tickets' },
    ],
  },
  {
    title: 'Help',
    module: 'help' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Help' },
      { key: 'view_help_articles', label: 'View Help Articles' },
      { key: 'create_help_articles', label: 'Create Help Articles' },
      { key: 'edit_help_articles', label: 'Edit Help Articles' },
      { key: 'delete_help_articles', label: 'Delete Help Articles' },
      { key: 'manage_help_categories', label: 'Manage Help Categories' },
    ],
  },
  {
    title: 'Settings',
    module: 'settings' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Settings' },
      { key: 'edit_settings', label: 'Edit Settings' },
      { key: 'manage_system_config', label: 'Manage System Config' },
      { key: 'manage_notifications', label: 'Manage Notifications' },
      { key: 'view_system_logs', label: 'View System Logs' },
      { key: 'manage_backup', label: 'Manage Backup' },
    ],
  },
  {
    title: 'Promotions',
    module: 'promotions' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Promotions' },
      { key: 'view_promotions', label: 'View Promotions' },
      { key: 'create_promotions', label: 'Create Promotions' },
      { key: 'edit_promotions', label: 'Edit Promotions' },
      { key: 'delete_promotions', label: 'Delete Promotions' },
      { key: 'manage_promotion_rules', label: 'Manage Promotion Rules' },
      { key: 'export_promotions', label: 'Export Promotions' },
    ],
  },
  {
    title: 'Delivery Settings',
    module: 'delivery_settings' as PrivilegeKey,
    permissions: [
      { key: 'access', label: 'Access Delivery Settings' },
      { key: 'view_delivery_settings', label: 'View Delivery Settings' },
      { key: 'edit_delivery_settings', label: 'Edit Delivery Settings' },
      { key: 'manage_delivery_zones', label: 'Manage Delivery Zones' },
      { key: 'manage_delivery_fees', label: 'Manage Delivery Fees' },
      { key: 'view_delivery_reports', label: 'View Delivery Reports' },
    ],
  },
]; 